name: Run Python Script

on: [push]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Replace with the version you need

      - name: Set up environment variables
        run: echo "GITHUB_TOKEN=${{ secrets.TT }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: python test.py # Replace 'your_script.py' with your Python file name

        
      
